# Generated by Django 4.1.2 on 2022-11-19 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
